version: 2

sources:
  - name: gz_raw_data
    description: raw fata from greenweez
    tables: 
      - name: raw_gz_product
        description: raw greenweez product data
      - name: raw_gz_sales
        description: raw greenweez sales data
      - name: raw_gz_ship
        description: raw greenweez shipping data 

      